/**
 * Maps country names to their Unicode flag emoji.
 * Covers all countries whose currencies appear in currencies.ts,
 * plus a broad set of commonly seen countries in analytics dashboards.
 */
export const countryFlags: Record<string, string> = {
  // ── Country codes ─────────────────────────────────────────────────────────
  IN: "🇮🇳",
  US: "🇺🇸",
  UK: "🇬🇧",
  GB: "🇬🇧",
  CA: "🇨🇦",
  AU: "🇦🇺",
  AE: "🇦🇪",
  SG: "🇸🇬",
  DE: "🇩🇪",
  FR: "🇫🇷",
  IT: "🇮🇹",
  ES: "🇪🇸",
  NL: "🇳🇱",
  CN: "🇨🇳",
  JP: "🇯🇵",
  KR: "🇰🇷",
  BR: "🇧🇷",
  MX: "🇲🇽",

  // ── Americas ──────────────────────────────────────────────────────────────
  "United States":        "🇺🇸",
  "Canada":               "🇨🇦",
  "Mexico":               "🇲🇽",
  "Brazil":               "🇧🇷",
  "Argentina":            "🇦🇷",
  "Chile":                "🇨🇱",
  "Colombia":             "🇨🇴",
  "Peru":                 "🇵🇪",
  "Venezuela":            "🇻🇪",
  "Ecuador":              "🇪🇨",
  "Bolivia":              "🇧🇴",
  "Paraguay":             "🇵🇾",
  "Uruguay":              "🇺🇾",

  // ── Europe ────────────────────────────────────────────────────────────────
  "United Kingdom":       "🇬🇧",
  "Germany":              "🇩🇪",
  "France":               "🇫🇷",
  "Italy":                "🇮🇹",
  "Spain":                "🇪🇸",
  "Netherlands":          "🇳🇱",
  "Switzerland":          "🇨🇭",
  "Sweden":               "🇸🇪",
  "Norway":               "🇳🇴",
  "Denmark":              "🇩🇰",
  "Finland":              "🇫🇮",
  "Belgium":              "🇧🇪",
  "Austria":              "🇦🇹",
  "Portugal":             "🇵🇹",
  "Poland":               "🇵🇱",
  "Czech Republic":       "🇨🇿",
  "Hungary":              "🇭🇺",
  "Romania":              "🇷🇴",
  "Greece":               "🇬🇷",
  "Turkey":               "🇹🇷",
  "Ukraine":              "🇺🇦",
  "Russia":               "🇷🇺",
  "Ireland":              "🇮🇪",
  "Luxembourg":           "🇱🇺",
  "Slovakia":             "🇸🇰",
  "Croatia":              "🇭🇷",
  "Serbia":               "🇷🇸",
  "Bulgaria":             "🇧🇬",

  // ── Asia-Pacific ─────────────────────────────────────────────────────────
  "India":                "🇮🇳",
  "China":                "🇨🇳",
  "Japan":                "🇯🇵",
  "South Korea":          "🇰🇷",
  "Singapore":            "🇸🇬",
  "Australia":            "🇦🇺",
  "New Zealand":          "🇳🇿",
  "Hong Kong":            "🇭🇰",
  "Taiwan":               "🇹🇼",
  "Indonesia":            "🇮🇩",
  "Malaysia":             "🇲🇾",
  "Thailand":             "🇹🇭",
  "Philippines":          "🇵🇭",
  "Vietnam":              "🇻🇳",
  "Bangladesh":           "🇧🇩",
  "Pakistan":             "🇵🇰",
  "Sri Lanka":            "🇱🇰",
  "Myanmar":              "🇲🇲",
  "Cambodia":             "🇰🇭",
  "Nepal":                "🇳🇵",

  // ── Middle East ───────────────────────────────────────────────────────────
  "United Arab Emirates": "🇦🇪",
  "Saudi Arabia":         "🇸🇦",
  "Israel":               "🇮🇱",
  "Qatar":                "🇶🇦",
  "Kuwait":               "🇰🇼",
  "Bahrain":              "🇧🇭",
  "Oman":                 "🇴🇲",
  "Jordan":               "🇯🇴",
  "Lebanon":              "🇱🇧",
  "Egypt":                "🇪🇬",
  "Iran":                 "🇮🇷",
  "Iraq":                 "🇮🇶",

  // ── Africa ────────────────────────────────────────────────────────────────
  "South Africa":         "🇿🇦",
  "Nigeria":              "🇳🇬",
  "Kenya":                "🇰🇪",
  "Ghana":                "🇬🇭",
  "Ethiopia":             "🇪🇹",
  "Tanzania":             "🇹🇿",
  "Uganda":               "🇺🇬",
  "Morocco":              "🇲🇦",
  "Algeria":              "🇩🇿",
  "Tunisia":              "🇹🇳",
  "Senegal":              "🇸🇳",
  "Ivory Coast":          "🇨🇮",
};
